project:
  name: aws-refarch-moodle
  owner: quickstart-eng@amazon.com
  regions:
  - us-east-2
  template: templates/01-existingvpc.yaml
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]